spring:
  freemarker:
    suffix: .ftl
    template-loader-path: /templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/oris
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Landrover2013}
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  application:
    name: tinyCian
  cloud:
    consul:
      config:
        enabled: false
      host: ${CONSUL_HOST:127.0.0.1}
      discovery:
        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        prefer-ip-address: true
        health-check-critical-timeout: "1m"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

jwt:
  secret: secretar

minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  accessKeyId: ShYeBAZWlbyUefy8
  accessKeySecret: CbvRAEmPxYKc6qWjEzSjpI2otZcMHlBA
  bucketName: tinycian

imageExtension: png, jpg, jpeg

logging:
  level:
    org:
      springframework: ERROR
    io:
      app: TRACE